In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load Excel file
df = pd.read_csv("Medicare_Hospital_Spending_by_Claim.csv")

In [ ]:
df.head()

,Facility Name,Facility ID,State,Period,Claim Type,Avg Spndg Per EP Hospital,Avg Spndg Per EP State,Avg Spndg Per EP National,Percent of Spndg Hospital,Percent of Spndg State,Percent of Spndg National,Start Date,End Date
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Home Health Agency,25,22,19,0.09%,0.08%,0.07%,01/01/2024,12/31/2024
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Hospice,2,2,1,0.01%,0.01%,0.00%,01/01/2024,12/31/2024
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Inpatient,28,45,46,0.10%,0.17%,0.17%,01/01/2024,12/31/2024
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Outpatient,116,135,208,0.43%,0.52%,0.76%,01/01/2024,12/31/2024
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Skilled Nursing Facility,9,14,17,0.03%,0.05%,0.06%,01/01/2024,12/31/2024

In [ ]:
df.shape

(63646, 13)

In [ ]:
df.columns

Index(['Facility Name', 'Facility ID', 'State', 'Period', 'Claim Type',
       'Avg Spndg Per EP Hospital', 'Avg Spndg Per EP State',
       'Avg Spndg Per EP National', 'Percent of Spndg Hospital',
       'Percent of Spndg State', 'Percent of Spndg National', 'Start Date',
       'End Date'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63646 entries, 0 to 63645
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Facility Name              63646 non-null  object
 1   Facility ID                63646 non-null  int64
 2   State                      63646 non-null  object
 3   Period                     63646 non-null  object
 4   Claim Type                 63646 non-null  object
 5   Avg Spndg Per EP Hospital  63646 non-null  int64
 6   Avg Spndg Per EP State     63646 non-null  int64
 7   Avg Spndg Per EP National  63646 non-null  int64
 8   Percent of Spndg Hospital  63646 non-null  object
 9   Percent of Spndg State     63646 non-null  object
 10  Percent of Spndg National  63646 non-null  object
 11  Start Date                 63646 non-null  object
 12  End Date                   63646 non-null  object
dtypes: int64(4), object(9)
memory usage: 6.3+ MB

In [ ]:
df.isnull().sum()

Facility Name                0
Facility ID                  0
State                        0
Period                       0
Claim Type                   0
Avg Spndg Per EP Hospital    0
Avg Spndg Per EP State       0
Avg Spndg Per EP National    0
Percent of Spndg Hospital    0
Percent of Spndg State       0
Percent of Spndg National    0
Start Date                   0
End Date                     0
dtype: int64

In [ ]:
#changing column names
df.columns=(df.columns.str.lower().str.replace(" ","_"))
df.columns

Index(['facility_name', 'facility_id', 'state', 'period', 'claim_type',
       'avg_spndg_per_ep_hospital', 'avg_spndg_per_ep_state',
       'avg_spndg_per_ep_national', 'percent_of_spndg_hospital',
       'percent_of_spndg_state', 'percent_of_spndg_national', 'start_date',
       'end_date'],
      dtype='object')

In [ ]:
#changing the date format
df['start_date']=pd.to_datetime(df['start_date'])
df['end_date']=pd.to_datetime(df['end_date'])

**Which claim types cost the most?**

For every type of medical claim, calculate the average hospital spending per episode, then rank them from highest spending to lowest.

In [ ]:
df.groupby(
    "claim_type"
)["avg_spndg_per_ep_hospital"].mean().sort_values(
    ascending=False
)

claim_type
Total                        25692.791912
Inpatient                     5152.454085
Skilled Nursing Facility      1469.210393
Carrier                       1173.137573
Outpatient                     389.009448
Home Health Agency             244.662634
Hospice                         78.321696
Durable Medical Equipment       57.471022
Name: avg_spndg_per_ep_hospital, dtype: float64

**Which hospitals spend the most?**

In [ ]:
df.groupby(["facility_id","facility_name"])["avg_spndg_per_ep_hospital"].mean().sort_values(ascending=False).head(10)

facility_id  facility_name
60124        ORTHOCOLORADO HOSP AT ST ANTHONY MED CAMPUS    4150.454545
280133       NEBRASKA SPINE HOSPITAL LLC                    4062.954545
50738        GREATER EL MONTE COMMUNITY HOSPITAL            4048.818182
670059       CHI ST LUKES LAKESIDE HOSPITAL                 3996.000000
370206       OKLAHOMA SPINE HOSPITAL                        3985.818182
440008       HENDERSON COUNTY COMMUNITY HOSPITAL            3963.590909
370192       NORTHWEST SURGICAL HOSPITAL                    3901.136364
130066       NORTHWEST SPECIALTY HOSPITAL                   3826.181818
230297       KARMANOS CANCER CENTER                         3782.000000
190266       THE SPINE HOSPITAL OF LOUISIANA                3775.454545
Name: avg_spndg_per_ep_hospital, dtype: float64

**Where is this hospital above national average?**

In [ ]:
df["difference_vs_national"] = (
    df["avg_spndg_per_ep_hospital"]
    -
    df["avg_spndg_per_ep_national"]
)

In [ ]:
print(df.columns.tolist())

['facility_name', 'facility_id', 'state', 'period', 'claim_type', 'avg_spndg_per_ep_hospital', 'avg_spndg_per_ep_state', 'avg_spndg_per_ep_national', 'percent_of_spndg_hospital', 'percent_of_spndg_state', 'percent_of_spndg_national', 'start_date', 'end_date', 'difference_vs_national']

In [ ]:
display(df.head())

,facility_name,facility_id,state,period,claim_type,avg_spndg_per_ep_hospital,avg_spndg_per_ep_state,avg_spndg_per_ep_national,percent_of_spndg_hospital,percent_of_spndg_state,percent_of_spndg_national,start_date,end_date,difference_vs_national
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Home Health Agency,25,22,19,0.09%,0.08%,0.07%,2024-01-01,2024-12-31,6
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Hospice,2,2,1,0.01%,0.01%,0.00%,2024-01-01,2024-12-31,1
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Inpatient,28,45,46,0.10%,0.17%,0.17%,2024-01-01,2024-12-31,-18
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Outpatient,116,135,208,0.43%,0.52%,0.76%,2024-01-01,2024-12-31,-92
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,1 to 3 days Prior to Index Hospital Admission,Skilled Nursing Facility,9,14,17,0.03%,0.05%,0.06%,2024-01-01,2024-12-31,-8

In [ ]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [ ]:
percentage_columns = [
    "percent_of_spndg_hospital",
    "percent_of_spndg_state",
    "percent_of_spndg_national"
]

for col in percentage_columns:
    # Check if the column is of object type (string-like) before applying .str accessor
    if df[col].dtype == 'object':
        df[col] = (
            df[col]
            .str.replace("%", "", regex=False)
            .astype(float)
        )
    # If it's already a numeric type but not float, ensure it's float
    elif not pd.api.types.is_float_dtype(df[col]):
        df[col] = df[col].astype(float)

In [ ]:
df[percentage_columns].head()

,percent_of_spndg_hospital,percent_of_spndg_state,percent_of_spndg_national
0,0.09,0.08,0.07
1,0.01,0.01,0.00
2,0.10,0.17,0.17
3,0.43,0.52,0.76
4,0.03,0.05,0.06

In [ ]:
#creating copy of dataset

df_clean=df.copy()

In [ ]:
df_clean[percentage_columns].head()

,percent_of_spndg_hospital,percent_of_spndg_state,percent_of_spndg_national
0,0.09,0.08,0.07
1,0.01,0.01,0.00
2,0.10,0.17,0.17
3,0.43,0.52,0.76
4,0.03,0.05,0.06

**KPI 1: How many hospitals are we benchmarking?**

In [ ]:
total_hospitals=df_clean["facility_id"].nunique()
print(total_hospitals)

2893

**KPI 2 – States Covered**

In [ ]:
total_states=df_clean["state"].nunique()
print(total_states)

50

***KPI 3 – Average Episode Cost (National Dataset)***

In [ ]:
episode_totals=df_clean[(df_clean["period"]=="Complete Episode")& (df_clean["claim_type"]=="Total")]

In [ ]:
episode_totals.head()

,facility_name,facility_id,state,period,claim_type,avg_spndg_per_ep_hospital,avg_spndg_per_ep_state,avg_spndg_per_ep_national,percent_of_spndg_hospital,percent_of_spndg_state,percent_of_spndg_national,start_date,end_date,difference_vs_national
21,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,Complete Episode,Total,26979,26206,27477,100.0,100.0,100.0,2024-01-01,2024-12-31,-498
43,MARSHALL MEDICAL CENTERS,10005,AL,Complete Episode,Total,23705,26206,27477,100.0,100.0,100.0,2024-01-01,2024-12-31,-3772
65,NORTH ALABAMA MEDICAL CENTER,10006,AL,Complete Episode,Total,25745,26206,27477,100.0,100.0,100.0,2024-01-01,2024-12-31,-1732
87,MIZELL MEMORIAL HOSPITAL,10007,AL,Complete Episode,Total,20397,26206,27477,100.0,100.0,100.0,2024-01-01,2024-12-31,-7080
109,CRENSHAW COMMUNITY HOSPITAL,10008,AL,Complete Episode,Total,21453,26206,27477,100.0,100.0,100.0,2024-01-01,2024-12-31,-6024

**KPI 4 – Average Episode Cost Across All Hospitals**

In [ ]:
average_episode_cost = episode_totals["avg_spndg_per_ep_hospital"].mean()
print(average_episode_cost)

25692.791911510543

**Highest-Cost Hospital**

In [ ]:
highest_cost_hospital = episode_totals.loc[
    episode_totals["avg_spndg_per_ep_hospital"].idxmax()
]

highest_cost_hospital

facility_name                ORTHOCOLORADO HOSP AT ST ANTHONY MED CAMPUS
facility_id                                                        60124
state                                                                 CO
period                                                  Complete Episode
claim_type                                                         Total
avg_spndg_per_ep_hospital                                          45654
avg_spndg_per_ep_state                                             28682
avg_spndg_per_ep_national                                          27477
percent_of_spndg_hospital                                          100.0
percent_of_spndg_state                                             100.0
percent_of_spndg_national                                          100.0
start_date                                           2024-01-01 00:00:00
end_date                                             2024-12-31 00:00:00
difference_vs_national                                             18177
Name: 10867, dtype: object

**State-Level Benchmarking**

In [ ]:
state_summary = (
    episode_totals
    .groupby("state")["avg_spndg_per_ep_hospital"]
    .mean()
    .reset_index()
)

In [ ]:
state_summary.head()

  state  avg_spndg_per_ep_hospital
0    AK               20754.125000
1    AL               22748.591549
2    AR               25671.000000
3    AZ               24925.098361
4    CA               27979.922509

In [ ]:
state_summary = state_summary.sort_values(
    by="avg_spndg_per_ep_hospital",
    ascending=False
)

In [ ]:
state_summary.head(10)